# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 723aca408c6cc519cb684b9601196225cf3dd273ffd212a9f6ebcb1b6c9aee39e92e18c02ad9668fa1568ea850a3319839bb6b5987a971e2c400b6d839e1c0a2

test:
  secret_key_base: 04f1f0b7e9529a0d987ced2afa564a159cd80177a2718466017ca65aaf63683c27f7d7f99778486c0981a66e730cb2324d95e2f015e8dacf4a9c858e08135d57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
